name: Deploy to Amazon ECS

# 1. 언제 이 로봇이 출동할 것인가? (main 브랜치에 코드가 push 될 때!)
on:
  push:
    branches:
      - main

# ★★★ 2. 실제 AWS 환경 이름 ★★★
env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: my-test-web-repo      
  ECS_CLUSTER: my-test-cluster     
  ECS_SERVICE: my-web-service     

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest # 로봇이 돌아갈 깡통 컴퓨터(리눅스)

    steps:
    # 1. 깃허브 창고에서 최신 코드 가져오기
    - name: Checkout source code
      uses: actions/checkout@v3

    # 2. 어제 금고에 숨겨둔 열쇠로 AWS 로그인 뚫기
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 3. ECR 창고 문 열기
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # 4. 도커 이미지 구워서(Build) ECR 창고로 쏘기(Push)
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    # 5. ECS 서비스에 "새로운 이미지 떴으니 다시 배포해!" 라고 강제 스위치 누르기
    - name: Force deployment to ECS
      run: |
        aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment
        
  # (새로 추가할 디스코드 알림 코드)
    - name: 디스코드 배포 성공 알림 보내기
      run: |
       curl -H "Content-Type: application/json" \
       -d '{"content": "🚀 hy0sk.cloud 배포 완료 "}' \          ${{ secrets.DISCORD_WEBHOOK }}    